Return-Path: <linux-hams-owner@vger.kernel.org>
X-Original-To: lists+linux-hams@lfdr.de
Delivered-To: lists+linux-hams@lfdr.de
Received: from vger.kernel.org (vger.kernel.org [23.128.96.18])
	by mail.lfdr.de (Postfix) with ESMTP id 5237B40FDCF
	for <lists+linux-hams@lfdr.de>; Fri, 17 Sep 2021 18:22:43 +0200 (CEST)
Received: (majordomo@vger.kernel.org) by vger.kernel.org via listexpand
        id S242022AbhIQQYE (ORCPT <rfc822;lists+linux-hams@lfdr.de>);
        Fri, 17 Sep 2021 12:24:04 -0400
Received: from trinity.trinnet.net ([96.78.144.185]:4003 "EHLO
        trinity3.trinnet.net" rhost-flags-OK-OK-OK-OK) by vger.kernel.org
        with ESMTP id S229979AbhIQQYE (ORCPT
        <rfc822;linux-hams@vger.kernel.org>); Fri, 17 Sep 2021 12:24:04 -0400
X-Greylist: delayed 1716 seconds by postgrey-1.27 at vger.kernel.org; Fri, 17 Sep 2021 12:24:04 EDT
Received: from trinity4.trinnet.net (trinity4.trinnet.net [192.168.0.11])
        by trinity3.trinnet.net (TrinityOS Hardened/TrinityOS Hardened) with ESMTP id 18HFs44l028180
        for <linux-hams@vger.kernel.org>; Fri, 17 Sep 2021 07:54:04 -0800
Subject: Re: unknown kiss packet: 0x80 0x9e
To:     linux-hams@vger.kernel.org
References: <654f3a4d-6420-4fba-e6d9-5693a67f6459@blackspace.at>
From:   David Ranch <linux-hams@trinnet.net>
Message-ID: <47ff7a73-dbe7-fcf3-f99f-36e63d709520@trinnet.net>
Date:   Fri, 17 Sep 2021 08:54:04 -0700
User-Agent: Mozilla/5.0 (X11; Linux i686; rv:45.0) Gecko/20100101
 Thunderbird/45.8.0
MIME-Version: 1.0
In-Reply-To: <654f3a4d-6420-4fba-e6d9-5693a67f6459@blackspace.at>
Content-Type: text/plain; charset=utf-8; format=flowed
Content-Transfer-Encoding: 7bit
X-Greylist: Sender IP whitelisted, not delayed by milter-greylist-3.0 (trinity3.trinnet.net [192.168.0.1]); Fri, 17 Sep 2021 07:54:04 -0800 (GMT+8)
Precedence: bulk
List-ID: <linux-hams.vger.kernel.org>
X-Mailing-List: linux-hams@vger.kernel.org


Hello Roland,

Are you trying to use Thomas Sailer's "soundmodem" program?  If so, it's 
quite old these days.  You will find that Direwolf or even G8BPQ's port 
of UZ7HO's "soundmodem" will offer better decoding rates, stability, etc.

--David
KI6ZHD



On 09/17/2021 08:21 AM, Roland Schwarz wrote:
> I am trying to use soundmodem and observe the following messages, 
> which apparently are generated by the ax25 driver:
>
> unknown kiss packet: 0x80 0x9e
> unknown kiss packet: 0x20 0x9e
>
> Are these codes known, or need I suspect an error in the packet 
> reading code? The soundmodem knows codes 0 to 8 and 255. Can anyone 
> point me to a resource where I could find out what these codes would 
> mean?
>
> tnx, de roland
>

